name: dbt_reciclagem
profile: dbt_reciclagem

models:
  dbt_reciclagem:
    bronze:
      +materialized: external
      +options:
        compression: snappy
      +external_root: '../data/bronze'
    # Camada Silver: Lê da Bronze e salva na pasta silver/
    silver:
      +materialized: external
      +options:
        compression: 'snappy'
        #partition_by: ['uf']
      +external_root: '../data/silver'
    # Camada Gold: Lê da Silver e salva na pasta gold/
    # gold:
    #   +materialized: external
    #   +options:
    #     compression: 'snappy'
    #   +external_root: '../data/gold'