name: dbt_reciclagem
profile: dbt_reciclagem

models:
  dbt_reciclagem:
    bronze:
      +materialized: table
    silver:
      +materialized: view
    gold:
      # +materialized: table
      +materialized: external
      +external_root: '../data/gold'
      +options:
        compression: 'snappy'
