dbt_reciclagem:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'data/estab_reciclagem.duckdb'
      extensions:
        - parquet
      settings:
        threads: 4
        memory_limit: '8GB'
